In [9]:
import pandas as pd
from sqlalchemy import create_engine, text

## Import CSV to Postgresql on Localhost

We import here the two census CSV tables to a localhost docker database 'basel_database'

In [ ]:
# Create the database connection URL
# Format: postgresql://user:password@host:port/database_name
db_url = "postgresql://postgres:secret@localhost:5432/basel_database"

# Create the SQLAlchemy engine
engine = create_engine(db_url)

### Import VS 1850

In [21]:
f_add = '/home/francesco/kDrive/kleioLab/Projekte/HISB_hotz_gerhard/daten_20260722/VZ_1850_H_END_20190701_inkl_Koordinaten.csv'

df = pd.read_csv(f_add, sep='\t')
df.head()

,Y_Koord_LV95,X_Koord_LV95,ID-Nr,Erstnennung_Adresse (ja),alte Haus-Nr,alte Haus-Nr nummerisch,Stadt_Gemeinde (wohnhaft),Quartier-Nummer,Quartier,Haushalte_pro_Adresse,...,Foto (Übertragungsbuch),Transkribierende (Name),Zeitraum der Transkription,Bemerkungen Transkription,Grunddatei für HISB (Dateiname),Datenkonsolidierung für HISB (Name),Datenkonsolidierung Datum,Problem: überprüfen (ja/nein/korr),Problem: Sachlage,Tr. Gegengelesen Datum
0,2.610822e+06,1.268376e+06,1,1.0,1,1.0,Gbas,1,St. Johann,2,...,VZ_1850_01_01.jpg,Verena Fiebig-Ebneter,1.10.2013-31.10.2014,NaN,VZ_1850_G3_20190701_END.xlsx,Gerhard Hotz,2019-03-12,nein,NaN,NaN
1,2.610822e+06,1.268376e+06,2,NaN,1,1.0,Gbas,1,St. Johann,2,...,VZ_1850_01_01.jpg,Verena Fiebig-Ebneter,1.10.2013-31.10.2014,NaN,VZ_1850_G3_20190701_END.xlsx,Gerhard Hotz,2019-03-12,nein,NaN,NaN
2,2.610822e+06,1.268376e+06,3,NaN,1,1.0,Gbas,1,St. Johann,2,...,VZ_1850_01_01.jpg,Verena Fiebig-Ebneter,1.10.2013-31.10.2014,NaN,VZ_1850_G3_20190701_END.xlsx,Gerhard Hotz,2019-03-12,nein,NaN,NaN
3,2.610822e+06,1.268376e+06,4,NaN,1,1.0,Gbas,1,St. Johann,2,...,VZ_1850_01_01.jpg,Verena Fiebig-Ebneter,1.10.2013-31.10.2014,NaN,VZ_1850_G3_20190701_END.xlsx,Gerhard Hotz,2019-03-12,nein,NaN,NaN
4,2.610822e+06,1.268376e+06,5,NaN,1,1.0,Gbas,1,St. Johann,2,...,VZ_1850_01_01.jpg,Verena Fiebig-Ebneter,1.10.2013-31.10.2014,NaN,VZ_1850_G3_20190701_END.xlsx,Gerhard Hotz,2019-03-12,nein,NaN,NaN

In [22]:
# Replace '(' and ')' with '_' in column names
df.columns = df.columns.str.replace(r'[()]', '_', regex=True)
df.columns = df.columns.str.replace(r'\s', '_', regex=True)
df.columns = df.columns.str.strip('_')
df.columns = df.columns.str.replace('__', '_')
df.columns = df.columns.str.replace('/', '_')
df.columns = df.columns.str.replace('-', '_')
df.columns = df.columns.str.replace('.', '')
df.columns = df.columns.str.lower()
df.iloc[:3, 10:20]

,haushalt_nr,bewohner_reihenfolge_hh,wohnungs_kennziffer,bewohner_reihenfolge_adresse,personen_pro_adresse_abs,name,vorname,geschlecht,alter_jahre,zivilstand
0,1,1,1-1,1,13,Sulger-Wohnlich,Rudolf,m,46,v
1,1,2,1-2,2,13,Sulger-Wohnlich,Catharina,f,45,v
2,1,3,1-3,3,13,Sulger,Catharina,f,14,l

In [23]:
print(df.columns)

Index(['y_koord_lv95', 'x_koord_lv95', 'id_nr', 'erstnennung_adresse_ja',
       'alte_haus_nr', 'alte_haus_nr_nummerisch', 'stadt_gemeinde_wohnhaft',
       'quartier_nummer', 'quartier', 'haushalte_pro_adresse', 'haushalt_nr',
       'bewohner_reihenfolge_hh', 'wohnungs_kennziffer',
       'bewohner_reihenfolge_adresse', 'personen_pro_adresse_abs', 'name',
       'vorname', 'geschlecht', 'alter_jahre', 'zivilstand', 'beruf_gewerbe',
       'geburtsjahr', 'konfession', 'abwesend', 'gemeindbürger_von',
       'staatszugehörigkeit', 'strasse_adressbuch_1854',
       'hausname_adressbuch_1854', 'stj_nr', 'kpr_personen_id_nr', 'kg_reg_nr',
       'spit_nr_1', 'spit_nr_2', 'spit_nr_3', 'spit_nr_4', 'spit_nr_5',
       'spit_nr_6', 'spit_nr_7', 'spit_nr_8', 'spit_nr_9',
       'quelle_übertragungsbuch', 'url_adresse_der_quelle_übertragungsbuch',
       'foto_übertragungsbuch', 'transkribierende_name',
       'zeitraum_der_transkription', 'bemerkungen_transkription',
       'grunddatei_für_hisb_dateiname', 'datenkonsolidierung_für_hisb_name',
       'datenkonsolidierung_datum', 'problem:_überprüfen_ja_nein_korr',
       'problem:_sachlage', 'tr_gegengelesen_datum'],
      dtype='object')

In [ ]:

# Save the DataFrame to a new PostgreSQL table
# if_exists='fail' raises an error if the table exists (use 'replace' to overwrite or 'append' to add)
df.to_sql('vz_1850', engine, schema='hisb_import', if_exists='fail', index=False)

In [18]:

with engine.connect() as conn:
     # conn.execute(text("ALTER TABLE hisb_import.vz_original ADD PRIMARY KEY (id_nr);"))
    conn.commit()

# Dispose the engine
engine.dispose()

### Import VS 1860

In [26]:
f_add = '/home/francesco/kDrive/kleioLab/Projekte/HISB_hotz_gerhard/daten_20260722/VZ_1860_H_END_20250402_inkl_Koordinaten_Abgabe_20260722.csv'

df = pd.read_csv(f_add, sep='\t')
df.head()

/tmp/ipykernel_130743/2000932898.py:3: DtypeWarning: Columns (12,13,16,24,27,39,40,41,42,44,46,48,68,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f_add, sep='\t')

,Y_Koord_LV95,X_Koord_LV95,ID-Nr,Erstnennung_Adresse (ja),alte Haus-Nr,alte Haus-Nr nummerisch,Stadt_Gemeinde (wohnhaft),Quartier-Nummer,Quartier,Haushalte_pro_Adresse,...,Zeitraum der Transkription,Bemerkungen Transkription,Grunddatei für HISB (Dateiname),Datenkonsolidierung für HISB (Name),Datenkonsolidierung Datum,Problem: überprüfen (ja/nein/korr),Problem: Sachlage,Tr. Gegengelesen (nein/Name),Tr. Gegengelesen Datum,Bemerkung Gegengelesung
0,2.610791e+06,1.268420e+06,1,1.0,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,NaN,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""Bürger anderer Kt oder Ausländer (syst. ...",NaN,NaN,NaN
1,2.610791e+06,1.268420e+06,2,NaN,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,NaN,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""Bürger anderer Kt oder Ausländer (syst. ...",NaN,NaN,NaN
2,2.610791e+06,1.268420e+06,3,NaN,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,NaN,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""alte Hausnummer"": Spezialfall: das St. J...",NaN,NaN,NaN
3,2.610791e+06,1.268420e+06,4,NaN,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,NaN,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""alte Hausnummer"": Spezialfall: das St. J...",NaN,NaN,NaN
4,2.610791e+06,1.268420e+06,5,NaN,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,NaN,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""alte Hausnummer"": Spezialfall: das St. J...",NaN,NaN,NaN

In [27]:
# Replace '(' and ')' with '_' in column names
df.columns = df.columns.str.replace(r'[()]', '_', regex=True)
df.columns = df.columns.str.replace(r'\s', '_', regex=True)
df.columns = df.columns.str.strip('_')
df.columns = df.columns.str.replace('__', '_')
df.columns = df.columns.str.replace('/', '_')
df.columns = df.columns.str.replace('-', '_')
df.columns = df.columns.str.replace('.', '')
df.columns = df.columns.str.lower()
df.iloc[:3, 10:20]

,haushalt_nr,zeddel_nummer,buch_zeddel_nummer,korr_war_buch_zeddel_nummer,bewohner_reihenfolge_hh,personen_pro_haushalt_abs,zimmerzahl_zeddel,zimmerzahl_buch,wohnungs_kennziffer,bewohner_reihenfolge_adresse
0,1.0,156,NaN,NaN,1,5,ka,ka,1-1,1
1,1.0,156,NaN,NaN,2,5,ka,ka,1-2,2
2,1.0,156,NaN,NaN,3,5,ka,ka,1-3,3

In [28]:
print(df.columns)

Index(['y_koord_lv95', 'x_koord_lv95', 'id_nr', 'erstnennung_adresse_ja',
       'alte_haus_nr', 'alte_haus_nr_nummerisch', 'stadt_gemeinde_wohnhaft',
       'quartier_nummer', 'quartier', 'haushalte_pro_adresse', 'haushalt_nr',
       'zeddel_nummer', 'buch_zeddel_nummer', 'korr_war_buch_zeddel_nummer',
       'bewohner_reihenfolge_hh', 'personen_pro_haushalt_abs',
       'zimmerzahl_zeddel', 'zimmerzahl_buch', 'wohnungs_kennziffer',
       'bewohner_reihenfolge_adresse', 'personen_pro_adresse_abs', 'name',
       'vorname', 'geschlecht', 'alter_jahre', 'zivilstand', 'beruf_gewerbe',
       'geburtsjahr', 'geburtsmonat_säugling', 'konfession', 'unterschrift',
       'abwesend', 'gemeindbürger_von', 'aufenthaltsverhältnisse',
       'bürger_anderer_kt_oder_ausländer_syst_nach_fiebig',
       'bürger_anderer_kantone_vereinheitlicht', 'staatszugehörigkeit',
       'heimatlose_und_findlinge', 'geburtsort', 'ordonanstutzer',
       'sonstige_stutzer', 'mit_perkussionszündung', 'mit_steinschloss',
       'strasse_adressbuch_1854', 'haus_nr_adressbuch_1854',
       'hausname_adressbuch_1854', '1854_an_gleicher_adresse_wohnhaft',
       'bemerkungen_allg_fiebig', 'stj_nr', 'kpr_personen_id_nr', 'kg_reg_nr',
       'spit_nr_1', 'spit_nr_2', 'spit_nr_3', 'spit_nr_4', 'spit_nr_5',
       'spit_nr_6', 'spit_nr_7', 'spit_nr_8', 'spit_nr_9',
       'quelle_zählungsbogen', 'id_nr_archiv_schachtel', 'bündel_bezeichnung',
       'url_adresse_der_quelle_zählungsbogen', 'foto_zählungsbogen',
       'quelle_übertragungsbuch', 'seite_buch_ab_nr_2494',
       'url_adresse_der_quelle_übertragungsbuch', 'foto_übertragungsbuch',
       'transkribierende_name', 'zeitraum_der_transkription',
       'bemerkungen_transkription', 'grunddatei_für_hisb_dateiname',
       'datenkonsolidierung_für_hisb_name', 'datenkonsolidierung_datum',
       'problem:_überprüfen_ja_nein_korr', 'problem:_sachlage',
       'tr_gegengelesen_nein_name', 'tr_gegengelesen_datum',
       'bemerkung_gegengelesung'],
      dtype='object')

In [29]:

# Save the DataFrame to a new PostgreSQL table
# if_exists='fail' raises an error if the table exists (use 'replace' to overwrite or 'append' to add)
df.to_sql('vz_1860', engine, schema='hisb_import', if_exists='fail', index=False)

22

In [ ]:
# Define your SQL query
query = "SELECT * FROM hisb_import.vz_1860"

# Execute query and load directly into a DataFrame
df = pd.read_sql_query(text(query), engine)

engine.dispose()

In [31]:
# Display the first few rows
df.head()

,y_koord_lv95,x_koord_lv95,id_nr,erstnennung_adresse_ja,alte_haus_nr,alte_haus_nr_nummerisch,stadt_gemeinde_wohnhaft,quartier_nummer,quartier,haushalte_pro_adresse,...,zeitraum_der_transkription,bemerkungen_transkription,grunddatei_für_hisb_dateiname,datenkonsolidierung_für_hisb_name,datenkonsolidierung_datum,problem:_überprüfen_ja_nein_korr,problem:_sachlage,tr_gegengelesen_nein_name,tr_gegengelesen_datum,bemerkung_gegengelesung
0,2.610791e+06,1.268420e+06,1,1.0,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,None,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""Bürger anderer Kt oder Ausländer (syst. ...",None,None,None
1,2.610791e+06,1.268420e+06,2,NaN,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,None,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""Bürger anderer Kt oder Ausländer (syst. ...",None,None,None
2,2.610791e+06,1.268420e+06,3,NaN,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,None,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""alte Hausnummer"": Spezialfall: das St. J...",None,None,None
3,2.610791e+06,1.268420e+06,4,NaN,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,None,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""alte Hausnummer"": Spezialfall: das St. J...",None,None,None
4,2.610791e+06,1.268420e+06,5,NaN,0,0.0,Gbas,1,St. Johann,1.0,...,1.11.2014-31.10.2016,None,VZ_1860_H_01_Johann_20190701_END.xlsx,Gerhard Hotz & Claudio Simoni,2019-07-01,ja,"Feld ""alte Hausnummer"": Spezialfall: das St. J...",None,None,None

In [32]:
print(df.columns)

Index(['y_koord_lv95', 'x_koord_lv95', 'id_nr', 'erstnennung_adresse_ja',
       'alte_haus_nr', 'alte_haus_nr_nummerisch', 'stadt_gemeinde_wohnhaft',
       'quartier_nummer', 'quartier', 'haushalte_pro_adresse', 'haushalt_nr',
       'zeddel_nummer', 'buch_zeddel_nummer', 'korr_war_buch_zeddel_nummer',
       'bewohner_reihenfolge_hh', 'personen_pro_haushalt_abs',
       'zimmerzahl_zeddel', 'zimmerzahl_buch', 'wohnungs_kennziffer',
       'bewohner_reihenfolge_adresse', 'personen_pro_adresse_abs', 'name',
       'vorname', 'geschlecht', 'alter_jahre', 'zivilstand', 'beruf_gewerbe',
       'geburtsjahr', 'geburtsmonat_säugling', 'konfession', 'unterschrift',
       'abwesend', 'gemeindbürger_von', 'aufenthaltsverhältnisse',
       'bürger_anderer_kt_oder_ausländer_syst_nach_fiebig',
       'bürger_anderer_kantone_vereinheitlicht', 'staatszugehörigkeit',
       'heimatlose_und_findlinge', 'geburtsort', 'ordonanstutzer',
       'sonstige_stutzer', 'mit_perkussionszündung', 'mit_steinschloss',
       'strasse_adressbuch_1854', 'haus_nr_adressbuch_1854',
       'hausname_adressbuch_1854', '1854_an_gleicher_adresse_wohnhaft',
       'bemerkungen_allg_fiebig', 'stj_nr', 'kpr_personen_id_nr', 'kg_reg_nr',
       'spit_nr_1', 'spit_nr_2', 'spit_nr_3', 'spit_nr_4', 'spit_nr_5',
       'spit_nr_6', 'spit_nr_7', 'spit_nr_8', 'spit_nr_9',
       'quelle_zählungsbogen', 'id_nr_archiv_schachtel', 'bündel_bezeichnung',
       'url_adresse_der_quelle_zählungsbogen', 'foto_zählungsbogen',
       'quelle_übertragungsbuch', 'seite_buch_ab_nr_2494',
       'url_adresse_der_quelle_übertragungsbuch', 'foto_übertragungsbuch',
       'transkribierende_name', 'zeitraum_der_transkription',
       'bemerkungen_transkription', 'grunddatei_für_hisb_dateiname',
       'datenkonsolidierung_für_hisb_name', 'datenkonsolidierung_datum',
       'problem:_überprüfen_ja_nein_korr', 'problem:_sachlage',
       'tr_gegengelesen_nein_name', 'tr_gegengelesen_datum',
       'bemerkung_gegengelesung'],
      dtype='object')

## Import Spital daten

In [33]:
f_add = '/home/francesco/kDrive/kleioLab/Projekte/HISB_hotz_gerhard/daten_20260722/KPR_1845_Gesamt_20260725_BEF.csv'

df = pd.read_csv(f_add, sep='\t')
df.head()

/tmp/ipykernel_130743/3856996543.py:3: DtypeWarning: Columns (5,6,14,15,17,21,31,52,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f_add, sep='\t')

,Kontrolle (to Do),Jahr,Woche,KG-Reg-Nr,BEM_KG-Reg-Nr,STJ-Nr,BEM_STJ-Nr,Spit-Nr,BEM_Spit-Nr,GTR-Nr,...,Zeitraum Verlinkung Ein-/Austritte,BEM_Verlinkung Ein-/Austritte,Verlinkung ext. Quellen (nein/Name),Zeitraum Verlinkung ext. Quellen,BEM_Verlinkung ext. Quellen,Datenkonsolidierung (Name),Datenkonsolidierung Datum,BEM_Datenkonsolidierung,Grunddatei für HISB (Dateiname),Datum Datentransfer HISB
0,NaN,1855,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,01/11/2022,NaN,Felicitas Ruch,01/11/2022,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1855,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,01/11/2022,NaN,Felicitas Ruch,01/11/2022,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1852,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.08.2020-15.08.2021,NaN,Regula Hotz,22.08.2020-15.08.2021,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1853,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.06.-16.07.2018 / 19.10.2020-27.01.2021,NaN,Regula Hotz,19.10.2020-27.01.2021,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1852,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.08.2020-15.08.2021,NaN,Regula Hotz,22.08.2020-15.08.2021,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
# Replace '(' and ')' with '_' in column names
df.columns = df.columns.str.replace(r'[()]', '_', regex=True)
df.columns = df.columns.str.replace(r'\s', '_', regex=True)
df.columns = df.columns.str.strip('_')
df.columns = df.columns.str.replace('__', '_')
df.columns = df.columns.str.replace('/', '_')
df.columns = df.columns.str.replace('-', '_')
df.columns = df.columns.str.replace('.', '')
df.columns = df.columns.str.lower()
df.iloc[:3, :10]

,kontrolle_to_do,jahr,woche,kg_reg_nr,bem_kg_reg_nr,stj_nr,bem_stj_nr,spit_nr,bem_spit_nr,gtr_nr
0,NaN,1855,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1855,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1852,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
print(df.columns)

Index(['kontrolle_to_do', 'jahr', 'woche', 'kg_reg_nr', 'bem_kg_reg_nr',
       'stj_nr', 'bem_stj_nr', 'spit_nr', 'bem_spit_nr', 'gtr_nr',
       'bem_gtr_nr', 'pfr_pers_id_nr', 'pfr_erst_eintritt_datum_jahr',
       'bem_pfr_pers_id_nr', 'vz_1850_pers_id_nr', 'bem_vz_1850_pers_id_nr',
       'vz_1860_pers_id_nr', 'bem_vz_1860_pers_id_nr', 'vz_1870_pers_id_nr',
       'bem_vz_1870_pers_id_nr', 'wohnsitz:_haushalt_pfrund_stadt',
       'bem_wohnsitz', 'abteilung', 'zi_nr', 'bem_abteilung', 'kpr_nr',
       'kpr_pers_id_nr', 'aufenthalts_nr', 'status_verlinkung', 'kpr_fam_nr',
       'bem_kpr_fam_nr', 'spital_eintritte', 'pfrund_eintritte',
       'haushalt_eintritte', 'name_vorname', 'biografie_kb', 'geschlecht',
       'ein__und_austritte', 'status_eintritt_austritt', 'eintritt_datum',
       'austritt_datum', 'gestorben_datum', 'eintritt_mm_dd_yyyy',
       'austritt_mm_dd_yyyy', 'dauer_tage', 'bem_verlinken',
       'ein__und_austritte1', 'pat_eintritt_nr', 'pat_uebertrag_austritt_nr',
       'pat_austritt_nr_kombi_feld', 'pat_austritt_nr',
       'pat_aus_int_abt_od_haush', 'pat_verlegt_in_abt', 'geburtsdaten',
       'quelle_geburtsdaten', 'ledigname', 'zivilstand', 'temporäre_mails_haf',
       'id_nr_ort', 'herkunft', 'bem_herkunft', 'herkunftsort_heute',
       'kanton___provinz', 'land', 'austritt_mit_kindbettkind', 'zugereist',
       'beruf___stand', 'bei,_in_,_von_,_wohnhaft',
       'kosten___gegen,_über_ihre_niederkunft___gegen_', 'im_spital',
       'zusätzliche_information', 'behinderung_krankheit_todesursache',
       'bemerkungen_allgemein', 'quelle_v_10___jahr;_v_12___jahr',
       'transkribierende_name', 'zeitraum_der_transkription',
       'bem_transkription', 'foto_buchseite', 'tr_gegengelesen_nein_name',
       'tr_gegengelesen_datum', 'bem_gegengelesen',
       'verlinkung_ein__austritte_nein_name',
       'zeitraum_verlinkung_ein__austritte', 'bem_verlinkung_ein__austritte',
       'verlinkung_ext_quellen_nein_name', 'zeitraum_verlinkung_ext_quellen',
       'bem_verlinkung_ext_quellen', 'datenkonsolidierung_name',
       'datenkonsolidierung_datum', 'bem_datenkonsolidierung',
       'grunddatei_für_hisb_dateiname', 'datum_datentransfer_hisb'],
      dtype='object')

In [37]:

# Save the DataFrame to a new PostgreSQL table
# if_exists='fail' raises an error if the table exists (use 'replace' to overwrite or 'append' to add)
df.to_sql('patientenregister', engine, schema='hisb_import', if_exists='fail', index=False)

46

In [38]:
# Define your SQL query
query = "SELECT * FROM hisb_import.patientenregister"

# Execute query and load directly into a DataFrame
df = pd.read_sql_query(text(query), engine)

engine.dispose()

In [39]:

# Display the first few rows
df.head()

,kontrolle_to_do,jahr,woche,kg_reg_nr,bem_kg_reg_nr,stj_nr,bem_stj_nr,spit_nr,bem_spit_nr,gtr_nr,...,zeitraum_verlinkung_ein_austritte,bem_verlinkung_ein_austritte,verlinkung_ext_quellen_nein_name,zeitraum_verlinkung_ext_quellen,bem_verlinkung_ext_quellen,datenkonsolidierung_name,datenkonsolidierung_datum,bem_datenkonsolidierung,grunddatei_für_hisb_dateiname,datum_datentransfer_hisb
0,None,1855,4,None,None,None,None,None,None,None,...,01/11/2022,None,Felicitas Ruch,01/11/2022,None,None,None,None,None,None
1,None,1855,4,None,None,None,None,None,None,None,...,01/11/2022,None,Felicitas Ruch,01/11/2022,None,None,None,None,None,None
2,None,1852,46,None,None,None,None,None,None,None,...,22.08.2020-15.08.2021,None,Regula Hotz,22.08.2020-15.08.2021,None,None,None,None,None,None
3,None,1853,1,None,None,None,None,None,None,None,...,7.06.-16.07.2018 / 19.10.2020-27.01.2021,None,Regula Hotz,19.10.2020-27.01.2021,None,None,None,None,None,None
4,None,1852,46,None,None,None,None,None,None,None,...,22.08.2020-15.08.2021,None,Regula Hotz,22.08.2020-15.08.2021,None,None,None,None,None,None

In [40]:
print(df.columns)

Index(['kontrolle_to_do', 'jahr', 'woche', 'kg_reg_nr', 'bem_kg_reg_nr',
       'stj_nr', 'bem_stj_nr', 'spit_nr', 'bem_spit_nr', 'gtr_nr',
       'bem_gtr_nr', 'pfr_pers_id_nr', 'pfr_erst_eintritt_datum_jahr',
       'bem_pfr_pers_id_nr', 'vz_1850_pers_id_nr', 'bem_vz_1850_pers_id_nr',
       'vz_1860_pers_id_nr', 'bem_vz_1860_pers_id_nr', 'vz_1870_pers_id_nr',
       'bem_vz_1870_pers_id_nr', 'wohnsitz:_haushalt_pfrund_stadt',
       'bem_wohnsitz', 'abteilung', 'zi_nr', 'bem_abteilung', 'kpr_nr',
       'kpr_pers_id_nr', 'aufenthalts_nr', 'status_verlinkung', 'kpr_fam_nr',
       'bem_kpr_fam_nr', 'spital_eintritte', 'pfrund_eintritte',
       'haushalt_eintritte', 'name_vorname', 'biografie_kb', 'geschlecht',
       'ein_und_austritte', 'status_eintritt_austritt', 'eintritt_datum',
       'austritt_datum', 'gestorben_datum', 'eintritt_mm_dd_yyyy',
       'austritt_mm_dd_yyyy', 'dauer_tage', 'bem_verlinken',
       'ein_und_austritte1', 'pat_eintritt_nr', 'pat_uebertrag_austritt_nr',
       'pat_austritt_nr_kombi_feld', 'pat_austritt_nr',
       'pat_aus_int_abt_od_haush', 'pat_verlegt_in_abt', 'geburtsdaten',
       'quelle_geburtsdaten', 'ledigname', 'zivilstand', 'temporäre_mails_haf',
       'id_nr_ort', 'herkunft', 'bem_herkunft', 'herkunftsort_heute',
       'kanton__provinz', 'land', 'austritt_mit_kindbettkind', 'zugereist',
       'beruf__stand', 'bei,_in_,_von_,_wohnhaft',
       'kosten__gegen,_über_ihre_niederkunft__gegen', 'im_spital',
       'zusätzliche_information', 'behinderung_krankheit_todesursache',
       'bemerkungen_allgemein', 'quelle_v_10__jahr;_v_12__jahr',
       'transkribierende_name', 'zeitraum_der_transkription',
       'bem_transkription', 'foto_buchseite', 'tr_gegengelesen_nein_name',
       'tr_gegengelesen_datum', 'bem_gegengelesen',
       'verlinkung_ein_austritte_nein_name',
       'zeitraum_verlinkung_ein_austritte', 'bem_verlinkung_ein_austritte',
       'verlinkung_ext_quellen_nein_name', 'zeitraum_verlinkung_ext_quellen',
       'bem_verlinkung_ext_quellen', 'datenkonsolidierung_name',
       'datenkonsolidierung_datum', 'bem_datenkonsolidierung',
       'grunddatei_für_hisb_dateiname', 'datum_datentransfer_hisb'],
      dtype='object')